pool: Nano-machine-sun

variables:
  System.Debug: true

stages:
- stage: Build
  jobs:
  - job: First
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
